In [1]:
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [2]:
import numpy
print(numpy.array([1,2,3]))

[1 2 3]


In [3]:
arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [4]:
arr_1 * 2

array([ 2,  4,  6,  8, 10])

In [5]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# 각 학급에 4명의 학생, 각 학생이 3과목의 시험 점수를 가지고 있는 배열 생성
# 예 : 3개의 학급, 각 학급에 4명의 학생, 각 학생당 국어, 영어 수학 점수
scores = np.random.randint(0,101,size=(3,4,3))

# 학급별, 학생ㅂ별, 과목별 점수 출력
print("학급별 학생들의 점수 배열 (3차원 배열)")
print(scores)

# 학급, 학생, 과목별로 점수 출력
for class_idx in range(scores.shape[0]):
    print(f"\nClass{class_idx + 1}")
    for student_idx in range(scores.shape[1]):
        korean, english, math = scores[class_idx, student_idx]
        print(f"Student {student_idx+1}-Korean:{korean}, English:{english}, Math:{math}")

학급별 학생들의 점수 배열 (3차원 배열)
[[[10  1 51]
  [ 0 64 12]
  [82 95 68]
  [ 0 43 39]]

 [[43 65 74]
  [29  4 68]
  [40 18 24]
  [ 1 84 11]]

 [[64 87  4]
  [26 76 56]
  [71 69 73]
  [97 49 47]]]

Class1
Student 1-Korean:10, English:1, Math:51
Student 2-Korean:0, English:64, Math:12
Student 3-Korean:82, English:95, Math:68
Student 4-Korean:0, English:43, Math:39

Class2
Student 1-Korean:43, English:65, Math:74
Student 2-Korean:29, English:4, Math:68
Student 3-Korean:40, English:18, Math:24
Student 4-Korean:1, English:84, Math:11

Class3
Student 1-Korean:64, English:87, Math:4
Student 2-Korean:26, English:76, Math:56
Student 3-Korean:71, English:69, Math:73
Student 4-Korean:97, English:49, Math:47


In [9]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
a = np.array([10,20,30,40])
b = np.arange(start=1,stop=5)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [12]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print(A*B)
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [13]:
A = np.array([1,2,3,4])
B = np.array([1,1,3,3])

print(A > B)
print(A == B)

[False  True False  True]
[ True False  True False]


In [15]:
# 두 명의 학생의 시험 점수를 배열로 생성
student1_scores = np.array([85,90,78]) # 학생 1의 점수
student2_scores = np.array([92,88,95]) # 학생 2의 점수

# 두 학생의 점수를 출력
print("학생 1의 점수 : ", student1_scores)
print("학생 2의 점수 : ", student2_scores)

# 두 학생의 총점을 구함
total_scores = student1_scores + student2_scores
print("두 학생의 총점 : ", total_scores)

# 두 학생의 평균 점수를 구함
average_scores = total_scores / 2
print("두 학생의 평균 : ", average_scores)

# 각 학생의 총점과 평균을 구합니다.
student1_total = np.sum(student1_scores)
student2_total = np.sum(student2_scores)
student1_average = round(np.mean(student1_scores),2)
student2_average = round(np.mean(student2_scores),2)

print("학생 1의 총점 : ", student1_total)
print("학생 2의 총점 : ", student2_total)
print("학생 1의 평균 : ", student1_average)
print("학생 2의 평균 : ", student2_average)

학생 1의 점수 :  [85 90 78]
학생 2의 점수 :  [92 88 95]
두 학생의 총점 :  [177 178 173]
두 학생의 평균 :  [88.5 89.  86.5]
학생 1의 총점 :  253
학생 2의 총점 :  275
학생 1의 평균 :  84.33
학생 2의 평균 :  91.67


In [1]:
import numpy as np

# A 배열 생성
A = np.array([4,16,25])
# 제곱근 함수
print(np.sqrt(A))

[2. 4. 5.]


In [2]:
a = np.arange(8).reshape(2,4)**2
print(a)

# 모든 요소의 합
print(a.sum())
# 모든 요소 중 평균
print(a.mean())
# 모든 요소 중 최솟값
print(a.min())
# 모든 요소 중 최댓값
print(a.max())
# 모든 요소의 누적합
print(a.cumsum())
# 모든 요소 중 최댓값의 인덱스
print(a.argmax())

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
0
49
[  0   1   5  14  30  55  91 140]
7


In [3]:
import numpy as np

# 0부터 8미만까지 출력하고 (2,4) 크기로 재가공하고 제곱하여 출력
# a= array([[0,1,4,9],
#           [16,25,36,49]])
a = np.arange(8).reshape(2,4)**2

# axis = 0은 열 기준으로 연산
print(a.mean(axis=0))
# axis = 1은 행 기준으로 연산
print(a.max(axis=1))

[ 8. 13. 20. 29.]
[ 9 49]


In [4]:
import numpy as np

a = np.array([0,1,2,3,4,5])
print(a)

# 인덱스가 0인, 인덱스가 3인 요소 출력
print(a[0])
print(a[3])

[0 1 2 3 4 5]
0
3


In [6]:
b = np.array([[0,1,2],[3,4,5]])
print(b)

# 인덱스가 [1,0]인, 인덱스가 [1,2]인 요소 출력
print(b[1,0])
print(b[1,2])

[[0 1 2]
 [3 4 5]]
3
5


In [7]:
import numpy as np

a = np.array([0,1,2,3,4,5])
print(a)

# 인덱스가 0 이상, 3미만 범위의 요소 출력
print(a[0:3])

[0 1 2 3 4 5]
[0 1 2]


In [8]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)

# a > 4 조건을 적용한 논리형 배열 생성
b = a > 4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [9]:
print(a[b]) # 논리형 배열 b를 사용해 조건에 맞는 요소 추출
print(a[b].shape) # 추출한 요소들의 배열 모양

[ 5  6  7  8  9 10 11]
(7,)


In [10]:
# 논리형 배열인 b를 이용하여 원본 a 배열의 값 변경하기 (True인 값의 위치에 변경하기)
a[b] = 1000
print(a)

[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [11]:
import numpy as np

a = np.array(['a','b','c','d','e','f','g','h'])
i = np.array([1,1,3,4])

# 배열 a에서 배열 i에 지정된 인덱스의 원소들을 출력
print(a[i])
j = np.array([[3,4],[5,6]])

# 배열 a에서 배열 j에 지정된 인덱스의 원소들을 출력
print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [12]:
b = np.array(['a','b','c','d'])
k = np.array([3,2,1,0])

# 배열 b에서 배열 k에 지정된 인덱스의 원소들을 재배열
b = b[k]
print(b)

['d' 'c' 'b' 'a']


In [13]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [14]:
# .reshape : 지정한 차원으로 변경하고 새로운 배열 반환
b = a.reshape(2,6)
print(b)
print(b.shape)

# 원본 a 배열은 기존의 (3,4) 형태 유지
print(a)
print(a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [15]:
import numpy as np

# .resize() : 지정한 차원으로 변경하고 원본 배열 자체를 변경
a = np.arange(12)
a.resize(4,3)
print(a)
print(a.shape)

# 따로 반환하는 값 없음
print(a.resize(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
None


In [16]:
import numpy as np

A = np.arange(12).reshape(2,6)
print(A)

# .T : [2,6]을 [6,2] 반환으로 전치(transpose) 변환
print(A.T)
print(A.T.shape)

# 만약 전치 형태로 원본 A 배열에 저장하고 싶다면, A배열에 A.T 값을 할당
A = A.T
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)


In [17]:
import numpy as np

# a 배열, b 배열 생성
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)

# 수직으로 합치기
print(np.vstack((a,b)))
# 수평으로 합치기
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [18]:
import numpy as np

# a 배열, b 배열 생성
a = np.arange(12).reshape(2,6)
print(a)

# 수직으로 분할하기
print(np.vsplit(a,2))
# 수평으로 분할하기
print(np.hsplit(a,3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
